version: 0.2

env:
  variables:
    #JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
    NODE_OPTIONS: "--max_old_space_size=8192"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - npm install yarn -g
      #- cd client && yarn install
      - yarn install
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - export NODE_OPTIONS=--max_old_space_size=8192
      - echo $NODE_OPTIONS
      #- cd ../client && yarn run build
      - yarn run build
      #- yarn run build-i18n:en - yarn run build-i18n:es - yarn run build-i18n:fr - yarn run build-i18n:jp
      #- mkdir ../server/public
      #- cp -R ./dist/client/* ../server/public/

    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

artifacts:
  files:
    #- 'server/**/*'
    - "build/**/*"
    #- 'scripts/**/*'
    - "appspec.yml"
  name: oostaoo
