import { AppProps } from 'next/app';
import Head from 'next/head';
import { ThemeProvider } from '@mui/material/styles';
import DataContextProvider from '@/context/context';

import '../styles/index.css';
import theme from '../styles/theme';

const MyApp = ({ Component, pageProps }: AppProps) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <DataContextProvider>

      <ThemeProvider theme={theme}>
        {/* eslint-disable-next-line */}
        <Component {...pageProps} />
      </ThemeProvider>
    </DataContextProvider>
  </>
);

export default MyApp;
