import JobOffers from "@/components/JobOffers/JobOffers";
import Nav from "@/components/Nav/Nav";
import Services from "@/components/Services/Services";
import Head from "next/head";
import styles from "./Home.module.css";
import Intro from "@/components/Intro/Intro";
import HeaderHero from "@/components/HeaderHero/HeaderHero";
import ContactForm from "@/components/ContactForm/ContactForm";
import { Technos } from "@/components/Technos/Technos";
import { References } from "@/components/References/References";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <div className={styles.ghostContainer} id="accueil"></div>
        <HeaderHero text={"Trouvez le talent que vous cherchez"} />
        <Intro />
        <Services />
        <Technos />
        <References />
        <JobOffers />
        <HeaderHero text={"Contactez-nous !"} />
        <ContactForm />
      </main>
    </>
  );
}
